"use strict";
require("dotenv").config();
const express=require("express"),cors=require("cors"),NodeCache=require("node-cache"),Groq=require("groq-sdk");
const {scrapeMobile}=require("./scrapers/mobile"),{scrapeAutoScout}=require("./scrapers/autoscout");
const app=express(),cache=new NodeCache({stdTTL:600}),groq=new Groq({apiKey:process.env.GROQ_API_KEY});
app.use(cors());app.use(express.json({limit:"2mb"}));
async function groqCall(sys,usr,max=800){const r=await groq.chat.completions.create({model:"llama-3.3-70b-versatile",messages:[{role:"system",content:sys},{role:"user",content:usr}],max_tokens:max,temperature:0.3});return r.choices[0]?.message?.content?.trim()||"";}
app.get("/",(_, res)=>res.json({ok:true,service:"AutoAI Backend",ai:"Groq llama-3.3-70b"}));
app.get("/health",(_, res)=>res.json({ok:true,ai:"Groq llama-3.3-70b"}));
app.post("/search",async(req,res)=>{try{const f=req.body||{},key="s:"+JSON.stringify(f),hit=cache.get(key);if(hit)return res.json({listings:hit,cached:true});const[mob,as24]=await Promise.allSettled([scrapeMobile(f),scrapeAutoScout(f)]);const raw=[...(mob.status==="fulfilled"?mob.value:[]),...(as24.status==="fulfilled"?as24.value:[])];if(!raw.length)return res.status(502).json({error:"Keine Ergebnisse. Bitte PROXY_URL in Railway Variables eintragen (webshare.io)."});let listings=raw;try{const sub=raw.slice(0,20).map(c=>({id:c.id,make:c.make,model:c.model,year:c.year,km:c.km,price:c.price,fuel:c.fuel}));const t=await groqCall("Automobil-Marktanalyst. NUR JSON-Array zurückgeben.",`Für jedes Fahrzeug: marketAvg, valueRating("gut"|"ok"|"hoch"), valueNote. Array: [{"id":"...","marketAvg":0,"valueRating":"ok","valueNote":"..."}]\n${JSON.stringify(sub)}`);const s=t.indexOf("["),e=t.lastIndexOf("]");if(s!==-1&&e>s){const en=JSON.parse(t.slice(s,e+1)),map=Object.fromEntries(en.map(x=>[x.id,x]));listings=raw.map(c=>({...c,...(map[c.id]||{})}));}}catch(e){console.warn("enrich skip",e.message);}listings=listings.slice(0,100);cache.set(key,listings);res.json({listings,sources:{"mobile.de":mob.status==="fulfilled"?mob.value.length:"Fehler","AutoScout24":as24.status==="fulfilled"?as24.value.length:"Fehler"}});}catch(e){res.status(500).json({error:e.message});}});
app.post("/chat",async(req,res)=>{try{const{message,listings=[],history=[]}=req.body;const sum=listings.slice(0,10).map(c=>`• ${c.make} ${c.model} (${c.year}, ${(c.km||0).toLocaleString("de-DE")} km, ${c.fuel}, ${c.power} PS) → ${(c.price||0).toLocaleString("de-DE")} € [${(c.valueRating||"ok").toUpperCase()}] – ${c.source}`).join("\n");const sys=`Du bist AutoBerater, KFZ-Experte. Echte Inserate:\n${sum||"Keine Suche."}\nAntworte auf Deutsch, max. 120 Wörter, kein Markdown.`;const msgs=[{role:"system",content:sys},...history.slice(-6).map(m=>({role:m.role==="ai"?"assistant":"user",content:m.text})),{role:"user",content:message}];const c=await groq.chat.completions.create({model:"llama-3.3-70b-versatile",messages:msgs,max_tokens:400,temperature:0.4});res.json({reply:c.choices[0]?.message?.content?.trim()||"Keine Antwort."});}catch(e){res.status(500).json({error:e.message});}});
app.post("/verdict",async(req,res)=>{try{const c=req.body;const t=await groqCall("KFZ-Experte. Max. 60 Wörter auf Deutsch.",`${c.make} ${c.model} ${c.variant||""}, Bj.${c.year}, ${(c.km||0).toLocaleString("de-DE")} km, ${c.fuel}, ${c.power} PS → ${(c.price||0).toLocaleString("de-DE")} €. Marktschnitt: ${(c.marketAvg||0).toLocaleString("de-DE")} €.`,200);res.json({verdict:t});}catch(e){res.status(500).json({error:e.message});}});
app.listen(process.env.PORT||3001,()=>console.log("AutoAI Backend | Groq llama-3.3-70b"));
